-- Standing rule: no production applicant data may ever be sourced into this
-- file, or into any dev/branch database.
--
-- Intentionally empty. The associate-2026 posting this used to insert is
-- already seeded by supabase/migrations/20260802231618_seed_associate_2026_job.sql
-- (same slug, on conflict do nothing), which runs through the real reviewed
-- migration path and reaches production too. This file used to duplicate
-- that insert, but drifted out of sync with the jobs table's columns after
-- 20260810120000_jobs_merge_description_fields.sql dropped
-- responsibilities/qualifications, breaking `supabase db reset` for anyone
-- running it fresh. Don't re-add job-posting inserts here -- add them as a
-- migration instead, same as that one did.
